import SideBar from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import Topbar from '@/components/Topbar'
import Providers from './providers'
import { GlobalContextProvider } from '@/context/store'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" dir='rtl' className='light' style={{ colorScheme: 'light' }}>
      <body className=' bg-light-secondary dark:bg-dark-primary flex'>
        <Providers>
          <GlobalContextProvider>
            <SideBar />
            <section className='flex-1 px-10'>
              <Topbar />
              <section className='mt-10'>
                {children}
              </section>
            </section>
          </GlobalContextProvider>
        </Providers>

      </body>
    </html>
  )
}
