import SideBar from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import Topbar from '@/components/Topbar'
import Providers from './providers'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en" dir='rtl'>
        <body className='bg-[#f3f3f3] flex'>
          <SideBar />
          <section className='flex-1'>
            <Topbar />
            {children}
          </section>
        </body>
      </html>
    </Providers>
  )
}
